name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: machine
    attributes:
      label: Machine Model
      description: What model was being patched?
      options:
        - iMac11,2
        
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Application Version
      description: What build version of our software are you running?
      options:
        - Latest Build (nightly)
        - Latest Release
    validations:
      required: true
  - type: dropdown
    id: variant
    attributes:
      label: Application Variant
      description: What variant of our software are you running?
      options:
        - GUI (Graphical User Interface)
        - CLI (Command Line Interface)
        - Other/Non-Applicable
    validations:
      required: true
  - type: dropdown
    id: verify-previously-reported
    attributes:
      label: Have you verified whether this issue has been opened before? If no, your issue will be closed
      description: If no, your issue will be closed. We'd appreciate it if users check with Github Issue's search before filing (https://github.com/dortania/OpenCore-Legacy-Patcher/issues?q=is%3Aissue)
      multiple: true
      options:
        - 'true'
        - 'false'
    validations:
      required: true
  - type: dropdown
    id: verify-guide
    attributes:
      label: Have you verified whether this issue is covered in our guide? ie. Troubleshooting and Legacy Acceleration pages
      description: If no, your issue will be closed. We'd appreciate it if users check with Guide before filing (https://dortania.github.io/OpenCore-Legacy-Patcher/)
      multiple: true
      options:
        - 'true'
        - 'false'
    validations:
      required: true
  - type: dropdown
    id: used-forums
    attributes:
      label: Have you already verified this is a patcher bug and not a macOS bug/user error on our discord servers?
      description: If no, please do not use issues for this. We'd appreciate it if users check discuss with others before filing. Issues are for valid patcher issues only, not for personal troubleshooting secessions.
      multiple: true
      options:
        - 'true'
        - 'false'
    validations:
      required: true
  - type: dropdown
    id: 3rd-party-application
    attributes:
      label: Is this issue with a 3rd party application?
      description: If yes, please move discussions onto forums. We're unable to dedicate time to working on every single application that may be broken in macOS. Only file issues if you have a fix you'd like to add to our project
      multiple: true
      options:
        - 'true'
        - 'false'
    validations:
      required: true
  - type: dropdown
    id: os-version
    attributes:
      label: What versions of macOS are you seeing the problem on?
      multiple: true
      options:
        - macOS 12, Monterey
        - macOS 11, Big Sur
        - macOS 10.15, Catalina
        - macOS 10.14, Mojave
        - macOS 10.13, High Sierra
        - macOS 10.12, Sierra
        - macOS 10.11, El Capitan
        - Other/Non-Applicable
    validations:
      required: true
  - type: dropdown
    id: where-issue
    attributes:
      label: Where does this issue happen?
      multiple: true
      options:
        - Between booting macOS and Login Screen
        - Within macOS (Before Logging in)
        - Within macOS (After Logging in)
        - Other/Non-Applicable
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the Issue?
      description: Additionally, explain what you expected to happen?
      value: "Please clearly explain the issue"
    validations:
      required: true
  - type: textarea
    id: extra-info
    attributes:
      label: What steps have you taken to troubleshoot this? Please include messages from Discord, logs, and screenshots.
